services:
  web2mp3:
    build: .
    image: ghcr.io/mgpoirot/web2mp3:latest
    init: true
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file: .env
    volumes:
      - ${HOST_MUSIC_DIR}:/music
      - ./.config:/app/.config
      - ./.logs:/app/.logs
      - ./src/index:/app/src/index
    tmpfs:
      - /app/.daemons
